### ISSUE TITLE
Undefined loadBase64Image error when using .toImage()

### ISSUE THREAD

**Issue by ugonnanwosu** [snorpey/glitch-canvas#10]
In dist/glitch-canvas.js `loadBase64Image` is undefined on line #431:17

```javascript
loadBase64Image(base64URL).then(resolve, reject);
```

**Comment by snorpey** [comment]
hey @ugonnanwosu thank you for reporting the bug!
i just pushed a fix for this issue, so version ``1.0.2`` should work for you. please let me know if you encounter any other problems.
