### ISSUE TITLE
is it possible to use glitched image as a backround for a DIV?

### ISSUE THREAD

**Issue by ser** [snorpey/glitch-canvas#12]
Hi,
is it possible to use the output as a _background_ for a DIV? If yes, how?

A code like this, which is for static images:

```
<div class="fullscreen background" style="background-image:url('http://www.minimit.com/images/picjumbo.com_IMG_6648.jpg');" data-img-width="1600" data-img-height="1064">
```

**Comment by snorpey** [comment]
hey @ser, thank you for your interest in this project.
to your question: yes, background images are possible with a bit javascript code.

assuming you have your directory setup like this:

	├── 01.html
	├── IMG_6648.jpg
	└── glitch-canvas-with-polyfills.js

this code should work

	<doctype html>
	<html>
		<head>
			<meta charset="utf-8"/>
			<title>glitched background image</title>
		</head>
		<style>
		.my-glitched-div { color: green;, background-size: cover; width: 400px; height: 200px; }
		</style>
		<body>
			<div class="my-glitched-div">
				THIS DIV HAS A GLITCHED BACKGROUND IMAGE
			</div>
			<script src="glitch-canvas-with-polyfills.js"></script>
			<script>
	var divEl = document.querySelector( '.my-glitched-div' );
	var myImage = new Image();
	myImage.onload = function () {
		glitch()
			.fromImage( myImage )
			.toDataURL()
			.then( function ( dataURL ) {
				divEl.style.backgroundImage = 'url(' + dataURL + ')';
			} );
	};
	myImage.src = 'IMG_6648.jpg';
			</script>
		</body>
	</html>
