### ISSUE TITLE
How to make this loop

### ISSUE THREAD

**Issue by adamjw3** [snorpey/glitch-canvas#14]
if i want this to run more than once on an image like here https://augaware.org/

what is the best way? 

i have this function, would i just call it over and over again to generate the random glitch?

```
imageGlitch: function () {
        var item = document.getElementsByClassName("js-top-places"),
            canvas = item[0],
            ctx = item[0].getContext('2d'),
            path = "resources/images/test/",
            w = canvas.clientWidth,
            h = (616 / 555) * canvas.clientWidth;
            canvas.height = h;
            canvas.width = w;

        // the parameters listed are the default params
        var glitchParams = {
            seed: Math.floor(Math.random() * (99 - 0 + 1)) + 0, // integer between 0 and 99 - default 20
            quality:  Math.floor(Math.random() * (80 - 40 + 1)) + 40, // integer between 0 and 99 - default 30
            amount: Math.floor(Math.random() * (99 - 25 + 1)) + 25, // integer between 0 and 99 - default 35
            iterations: Math.floor(Math.random() * (25 - 5 + 1)) + 25 // integer - default 20
        };

        var image = new Image();

        image.onload = function () {
            glitch(glitchParams)
                .fromImage(image)
                .toImageData()
                .then(function (imageData) {
                    ctx.drawImage(image, 0, 0, w, h, 0, 0, w, h);
                    ctx.putImageData(imageData, 0, 0);
                });
        };

        image.src = path + canvas.getAttribute("data-img");

    },
```

**Comment by snorpey** [comment]
hey @adamjw3 thank you for your interest in this library! i'm really glad you want to use it.

it is possible to just call the glitch function in an animaion loop. but since the glitch calculation is a bit processor intensive i think it makes more sense to create a few glitched images in advance and cache them for instant playback.

this is how it looks in code:

		<doctype html>
		<html>
		<canvas class="js-top-places" data-img="test.jpg"></canvas>

		<script src="glitch-canvas.js"></script>
		<script>
			function glitchItem () {
				var item = document.getElementsByClassName("js-top-places"),
					canvas = item[0],
					ctx = item[0].getContext('2d'),
					// path = "resources/images/test/",
					path = '', // just changed this for testing purposes
					w = canvas.clientWidth,
					h = (616 / 555) * canvas.clientWidth;
					canvas.height = h;
					canvas.width = w;

				var image = new Image();

				var framesCache = [ ];
				var currentFrameIndex = 0;
				var isAnimating = false;
				var fps = 10;

				image.onload = function () {
					generateGlitchedImageData( 4, image ).then( function ( frames ) {
						framesCache = frames;
						canvas.addEventListener( 'click', toggleAnimation );
						startAnimation();
					} );
				};

				image.src = path + canvas.getAttribute("data-img");

				function startAnimation () {
					isAnimating = true;
					showNextFrame();
				}

				function stopAnimation () {
					isAnimating = false;
				}

				function toggleAnimation () {
					if ( isAnimating ) {
						stopAnimation();
					} else {
						startAnimation();
					}
				}

				// animate to one of the cached frames
				function showNextFrame () {
					if ( isAnimating ) {
						if ( framesCache.length ) {
							currentFrameIndex++;
							
							if ( currentFrameIndex > framesCache.length - 1 ) {
								currentFrameIndex = 0;
							}
						}

						requestAnimationFrame( function () {
							ctx.putImageData( framesCache[currentFrameIndex], 0, 0 );
							setTimeout( showNextFrame, 1000 / fps );
						} );
					}
				}
			}

			// create a few different glitched images
			function generateGlitchedImageData ( frameCount, image ) {
				var glitchPromses = [ ];

				for ( var i = 0; i < frameCount; ++i ) {
					glitchPromses[i] = glitch( getRandomGlitchParams() )
						.fromImage(image)
						.toImageData();
				}

				return Promise.all( glitchPromses );
			}

			// return different params every time
			function getRandomGlitchParams () {
				return {
					seed: Math.floor(Math.random() * (99 - 0 + 1)) + 0, // integer between 0 and 99 - default 20
					quality:  Math.floor(Math.random() * (80 - 40 + 1)) + 40, // integer between 0 and 99 - default 30
					amount: Math.floor(Math.random() * (99 - 25 + 1)) + 25, // integer between 0 and 99 - default 35
					iterations: Math.floor(Math.random() * (25 - 5 + 1)) + 25 // integer - default 20
				};
			}

			glitchItem();
		</script>

let me know if you have questions or need me to clarify something.

also if you're interested how exactly the library was used on the aug aware site, maybe @ugonnanwosu can give you a pointer in the right direction.

**Comment by adamjw3** [comment]
Thanks that works but if i change fps or framecount i get 

Uncaught (in promise) Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0…}

I can't seem to find anyway of contacting @ugonnanwosu to ask him about how he implemented it.

is everything controlled within the params for seed, quality, amount and iterations?

**Comment by snorpey** [comment]
hey @adamjw3,
glad to see you can get it to work.

would you mind sharing the exact code that you're having trouble with? and maybe the share the image in question as well? it's kind of tricky to debug it otherwise

maybe you can even use a snippet sharing service like https://gist.gitlab.com or https://jsbin.com or https://jsfiddle.net/ ?
thank you!

**Comment by adamjw3** [comment]
i've added on here https://jsfiddle.net/adamjw3/me8k8sk6/ and updated the fps to 20 and the frameCount to 90.

**Comment by snorpey** [comment]
hey @adamjw3, thanks for creating the jsfiddle.

i noticed a you are trying to glitch a gif image. unfortunately, animated gif images are not supported by glitch-canvas.

but in addition to that, it looks like some of the random glitch values don't work properly on small images. this is definitely a bug that i'll have to look into.

**Comment by snorpey** [comment]
closing this issue for now, the small size bug is tracked under #1
