### ISSUE TITLE
Error installing glitch-canvas from npm

### ISSUE THREAD

**Issue by hugocifre** [snorpey/glitch-canvas#17]
Hi snorpey,

First of all thanks for sharing your script with the community.

I have been trying to run it for a while now but I am quite a newbie with node and npm and when i try to install it i get some errors, which i don't know if are node/npm or glitch-canvas related. I would appreciate if you could give me a hand with it!

Thanks :)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-node"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! glitch-canvas@1.0.2 test-node: `mocha ./test/test-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glitch-canvas@1.0.2 test-node script 'mocha ./test/test-node.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glitch-canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha ./test/test-node.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs glitch-canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls glitch-canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hugocifre/Desktop/glitch-canvas-master/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! glitch-canvas@1.0.2 test: `npm run test-node && npm run test-browser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glitch-canvas@1.0.2 test script 'npm run test-node && npm run test-browser'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glitch-canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test-node && npm run test-browser
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs glitch-canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls glitch-canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hugocifre/Desktop/glitch-canvas-master/npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.2 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! glitch-canvas@1.0.2 prepublish: `npm run build && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glitch-canvas@1.0.2 prepublish script 'npm run build && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glitch-canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs glitch-canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls glitch-canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hugocifre/Desktop/glitch-canvas-master/npm-debug.log

**Comment by snorpey** [comment]
hey @hugocifre thank you for your interest in this project!

I'm having a hard time reproducing this issue. Could you let me know which operating system you're using?

Also, this library depends on [node-canvas](https://github.com/Automattic/node-canvas/tree/v1.x#installation) internally, which – depending on your operating system – may require you to install some additional software.

Let me know if this helps. Thank you!

**Comment by snorpey** [comment]
hey @hugocifre i just published a new version that should fix your issue.
