### ISSUE TITLE
Use web workers

### ISSUE THREAD

**Issue by MaximilianLloyd** [snorpey/glitch-canvas#18]
I am currently using this library to apply a glitch effect to the images every 2.5 seconds. But after a while it starts lagging massively and halting the main thread. Wouldn't it be better to use web workers for the processing of the images?

**Comment by snorpey** [comment]
hey @MaximilianLloyd,

thank you for using this library. it is actually using web workers for some of the calculations (see [src/workers/glitchWorker.js](../blob/master/src/workers/glitchWorker.js)). unfortunately, web workers don't have access to the actual canvas elements, so only a small part of the calculation can happen in the workers.

if you could provide a little test case for your scenario, it would help me a lot with fixing performance issues.

**Comment by MaximilianLloyd** [comment]
Ok, I'll set up an example :-).

**Comment by MaximilianLloyd** [comment]
When I open the website on my machine at home the problem is no longer there. Perhaps it was only specific to my work machine. Sorry about that.

**Comment by snorpey** [comment]
ok, cool. closing this issue for now. feel free to ping me if this problem resurfaces. thanks for your help!
