### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Kingbalou** [snorpey/glitch-canvas#22]
Hi,
is there any way to use it on nodeJs server without any view or client rendering ? 

I used your exemple : 

```
var inputStream = fs.createReadStream(filename);
var outputStream = fs.createWriteStream( 'glitched/'+filename );

glitch()
  .fromStream( inputStream )
  .toPNGStream()
  .then( function ( pngStream ) {
      pngStream.on( 'data', function ( chunk ) { outputStream.write( chunk ); } );
      pngStream.on( 'end', function () { console.log( 'png file saved.' ); } );
  } );
```

but as a result i've only this error : `ReferenceError: window is not defined`

Any help ?

**Comment by snorpey** [comment]
hey @Kingbalou thank you for reporting this bug.

for some reason, it doesn't seem to load the correct script yet.

i'm not quite sure how to fix this yet, but i'll let you know once i have fixed it.

if you need to fix this urgently, you could probably try to copy + paste the `dist-node` folder into your project and then import it like so: `var glitch = require('./dist-node/index.js');` (you can also check out the `examples` folder in this repo).

**Comment by Kingbalou** [comment]
Just tried your solution and now it says :
`Error: Cannot find module 'canvas'`

Maybe i'm missing something ?

**Comment by snorpey** [comment]
@Kingbalou have you installed node-canvas? `npm install canvas`

**Comment by Kingbalou** [comment]
Nop , i'm doing it right now and I keep you informed

**Comment by Kingbalou** [comment]
Crappy canvas package, so i'll try when i've more time to spend on it .

Keep throwing error on build even with dependencies but i'll try later on Unix instead of Windows, it's easier.

**Comment by snorpey** [comment]
@Kingbalou sorry to hear that. i haven't tried it to run it on windows yet, so i'm afraid i can't help you much here... all i can do is wish you good luck...

i know that `node-canvas` is difficult to work with, but unfortunately it is the only way to use canvas in node (that i'm aware of).

let me know how it goes...

**Comment by Kingbalou** [comment]
Don't worry i know it can be difficult with some heavy package ;) 

i'm sure it will work perfectly on Unix !

**Comment by snorpey** [comment]
hey @Kingbalou i just published a new version that should fix your original issue.

**Comment by Kingbalou** [comment]
Wow thank's so much ! i'll try this wk ;)

**Comment by snorpey** [comment]
closing this issue for now... in case this is still a problem, let me know…
