### ISSUE TITLE
QUESTION Canvas 2.0?

### ISSUE THREAD

**Issue by YorkAARGH** [snorpey/glitch-canvas#46]
Is there any word, news or hope of a Canvas 2.0 supported version? I would love to use this, but I use Canvas 2.0 sadly.

**Comment by snorpey** [comment]
@YorkAARGH thank you for your interest in this project, and thank you for raising this issue.

I just looked into supporting `node-canvas` 2. You can have a look at my efforts in the [`canvas-2`](https://github.com/snorpey/glitch-canvas/tree/canvas-2) branch.

I was able to make it work with a version of `node-canvas` 2 (`2.0.0-alpha.11` to be exact), but I think it will take some time before I can merge `node-canvas@2` as a dependency to the master branch. In my opinion, it still needs some time to mature and get out of alpha.

Let me know if you have any questions or if this works for you.

Have a great day!

**Comment by YorkAARGH** [comment]
Thank you for getting back to me, I will test this out in my project and get back to you.

**Comment by YorkAARGH** [comment]
I'm not sure if I'm doing something wrong (extremely likely) or the code won't do what I want it to do.

I'm creating a canvas based API for the Discord communication platforms API, and I would love to have your glitch package apart of it, but when I go to use it [code](https://hastebin.com/pexasoruzo.js), it throws a `Corrupt JPEG data: premature end of data segment` error, here is the log.

```
1 'https://cdn.discordapp.com/avatars/146048938242211840/8e362e16040f47ea1d4054e85038da8c.jpg?size=512'
2 <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 08 06 06 07 06 05 08 07 07 07 09 09 08 0a 0c 14 0d 0c 0b 0b 0c 19 12 13 0f ... >
Corrupt JPEG data: premature end of data segment
3 <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 01 f4 00 00 01 f4 08 06 00 00 00 cb d6 df 8a 00 00 00 06 62 4b 47 44 00 ff 00 ff 00 ff a0 bd a7 ... >
4 undefined
```
The numbers in the above log correspond with the console logs in the code I supplied via hastebin

I've tried a bunch of different methods, besides saving the file to the server (which I do not want to do). Any and all insight you can provide will be fantastic

**Comment by snorpey** [comment]
when running tests / examples, I sometimes get the `Corrupt JPEG data: premature end of data segment` message as well. it doesn't seem to be an error though that I can `catch` (maybe I just haven't found out how), and the resulting glitched image data is correctly processed (saved as file or returned)

I'm still new to the `async/await` syntax, but I think in your example, the `getGlitched` function doesn't seem to return anything.

I hope this helps. Let me know if you find out more.

**Comment by snorpey** [comment]
@YorkAARGH i'll close this issue for now. let's reopen it if this doesn't work for you.

**Comment by snorpey** [comment]
@YorkAARGH fyi: i just updated the library to use version 2 of `canvas`
