### ISSUE TITLE
how to destroy the glitch instance ?

### ISSUE THREAD

**Issue by ctf0** [snorpey/glitch-canvas#50]
for example am using it inside a vuejs component but even when destroying the component, reinit glitch again still shows the same old results.

<br>

> PS

am trying to do something similar to the demo but i keep getting different results, any help on how to recreate it is appreciated.

**Comment by snorpey** [comment]
@ctf0 sorry I missed you opening the issue (didn't receive the github notification e-mail). were you able to resolve the issue?

**Comment by ctf0** [comment]
sadly no :(

**Comment by snorpey** [comment]
@ctf0 anc chance you could provide a simple test case for your issue? this would make it easier for me to fix the issue

**Comment by ctf0** [comment]
sure, atm am using the package with vuejs, the problem is when the component is removed from the dom completely and re-inited again the glitch data is still the same as the old because the glitch instance in window wasnt cleared.

adding a destroy method will make sure the glitch instance is cleared when needed

**Comment by snorpey** [comment]
@ctf0 could you provide a test case (with some code for me to look at) for your issue? i just want to make sure i understand the issue correctly. thank you!

**Comment by ctf0** [comment]
atm am using with a media package am building https://github.com/ctf0/Laravel-Media-Manager but i will try to provide u with a simpler example ex.`jsfiddle, etc..`

**Comment by ctf0** [comment]
thanx for ur work and ur patience, the issue was related to my logic.

thanx again

**Comment by snorpey** [comment]
thank you!
